language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew food-server:publishStubsPublicationToMavenLocal
  - ./gradlew clean build
after_success:
  - bash <(curl -s https://codecov.io/bash)