language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew food-server:publishStubsPublicationToMavenLocal
  - ./gradlew clean build
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)  -t cf8fd6b1-f6a9-43a4-85f9-348fcb228385